from datetime import datetime, timezone
from typing import Any, Dict, Optional
from sqlalchemy import Column, Integer, String, Float, DateTime, JSON, ForeignKey, Boolean
from sqlalchemy.orm import relationship
from database.connection import Base

class ConfigurationModel(Base):
    """Stores system-wide dynamic configuration values."""
    __tablename__ = "configurations"

    key = Column(String(100), primary_key=True)
    value = Column(String(500), nullable=False)
    description = Column(String(250), nullable=True)
    updated_at = Column(DateTime, default=lambda: datetime.now(timezone.utc), onupdate=lambda: datetime.now(timezone.utc))

    def __repr__(self) -> str:
        return f"<Configuration(key={self.key}, value={self.value})>"


class MarketDataModel(Base):
    """Stores historical and real-time market price data (ticks/candles)."""
    __tablename__ = "market_data"

    id = Column(Integer, primary_key=True, autoincrement=True)
    symbol = Column(String(50), nullable=False, index=True)
    timestamp = Column(DateTime, nullable=False, index=True)
    interval = Column(String(10), default="1m", nullable=False, index=True)  # tick, 1m, 5m, 1h, etc.
    open = Column(Float, nullable=False)
    high = Column(Float, nullable=False)
    low = Column(Float, nullable=False)
    close = Column(Float, nullable=False)
    volume = Column(Float, nullable=False)

    def __repr__(self) -> str:
        return f"<MarketData(symbol={self.symbol}, time={self.timestamp}, close={self.close})>"


class IndicatorModel(Base):
    """Stores calculated technical or ML indicators associated with symbols."""
    __tablename__ = "indicators"

    id = Column(Integer, primary_key=True, autoincrement=True)
    symbol = Column(String(50), nullable=False, index=True)
    name = Column(String(100), nullable=False, index=True)  # RSI, MACD, custom-ml-model
    timestamp = Column(DateTime, nullable=False, index=True)
    values = Column(JSON, nullable=False)  # Dictionary of calculated components

    def __repr__(self) -> str:
        return f"<Indicator(name={self.name}, symbol={self.symbol}, time={self.timestamp})>"


class OrderModel(Base):
    """Tracks state and parameters of trading orders."""
    __tablename__ = "orders"

    id = Column(String(100), primary_key=True)  # Client Order ID (uuid / custom prefix)
    broker_order_id = Column(String(100), nullable=True, index=True)
    symbol = Column(String(50), nullable=False, index=True)
    side = Column(String(10), nullable=False)  # BUY, SELL
    type = Column(String(20), nullable=False)  # MARKET, LIMIT, STOP_LIMIT
    price = Column(Float, nullable=True)
    quantity = Column(Float, nullable=False)
    status = Column(String(30), nullable=False, index=True)  # PENDING, SUBMITTED, FILLED, REJECTED, CANCELLED
    broker = Column(String(50), nullable=False)  # paper, kotak, etc.
    created_at = Column(DateTime, default=lambda: datetime.now(timezone.utc))
    updated_at = Column(DateTime, default=lambda: datetime.now(timezone.utc), onupdate=lambda: datetime.now(timezone.utc))

    # Relationship to trades
    trades = relationship("TradeModel", back_populates="order", cascade="all, delete-orphan")

    def __repr__(self) -> str:
        return f"<Order(id={self.id}, symbol={self.symbol}, side={self.side}, status={self.status})>"


class TradeModel(Base):
    """Tracks actual executions (fills) of orders."""
    __tablename__ = "trades"

    id = Column(String(100), primary_key=True)  # Trade execution ID from broker or system
    order_id = Column(String(100), ForeignKey("orders.id"), nullable=False, index=True)
    symbol = Column(String(50), nullable=False, index=True)
    side = Column(String(10), nullable=False)  # BUY, SELL
    price = Column(Float, nullable=False)
    quantity = Column(Float, nullable=False)
    commission = Column(Float, default=0.0)
    executed_at = Column(DateTime, default=lambda: datetime.now(timezone.utc), index=True)
    broker = Column(String(50), nullable=False)

    order = relationship("OrderModel", back_populates="trades")

    def __repr__(self) -> str:
        return f"<Trade(id={self.id}, order_id={self.order_id}, price={self.price}, quantity={self.quantity})>"


class AgentReportModel(Base):
    """Stores analytical outputs, heartbeats, or audits generated by agents."""
    __tablename__ = "agent_reports"

    id = Column(Integer, primary_key=True, autoincrement=True)
    agent_name = Column(String(100), nullable=False, index=True)
    report_type = Column(String(50), nullable=False, index=True)  # performance, risk_analysis, health
    data = Column(JSON, nullable=False)  # Arbitrary payload
    created_at = Column(DateTime, default=lambda: datetime.now(timezone.utc), index=True)

    def __repr__(self) -> str:
        return f"<AgentReport(agent={self.agent_name}, type={self.report_type})>"


class JournalModel(Base):
    """Stores logs, decisions, or text diaries (trading journal)."""
    __tablename__ = "journal"

    id = Column(Integer, primary_key=True, autoincrement=True)
    entry_type = Column(String(50), default="system", index=True)  # system, manual, risk_decision, strategy_note
    text = Column(String(2000), nullable=False)
    tags = Column(JSON, nullable=True)  # List of string tags ["BTC", "risk_limit", "cooldown"]
    created_at = Column(DateTime, default=lambda: datetime.now(timezone.utc), index=True)

    def __repr__(self) -> str:
        return f"<Journal(type={self.entry_type}, time={self.created_at})>"


class PerformanceModel(Base):
    """Stores periodic snapshots of portfolio health metrics."""
    __tablename__ = "performance"

    id = Column(Integer, primary_key=True, autoincrement=True)
    equity = Column(Float, nullable=False)
    pnl = Column(Float, nullable=False)
    drawdown_percent = Column(Float, nullable=False)
    sharpe_ratio = Column(Float, default=0.0)
    metrics = Column(JSON, nullable=True)  # Dictionary containing win_rate, total_trades, profit_factor etc.
    timestamp = Column(DateTime, default=lambda: datetime.now(timezone.utc), index=True)

    def __repr__(self) -> str:
        return f"<Performance(equity={self.equity}, pnl={self.pnl}, time={self.timestamp})>"


class StrategyDefinitionModel(Base):
    """
    Standardized, engine-agnostic strategy definition produced by the
    Strategy Studio. `definition` is a JSON blob matching the
    strategies.models.Strategy pydantic schema (rules, exit_rules, actions)
    — the same schema strategies/engine.py already evaluates, and the same
    one YAML-file strategies use, so any consumer (live decision pipeline,
    backtest replay, future modules) reads strategies the same way
    regardless of where they were authored.

    Versioned: every save is a new immutable row. Exactly one version per
    strategy_name may have is_active=True at a time — that's the version
    StrategyEngine loads and evaluates.
    """
    __tablename__ = "strategy_definitions"

    id = Column(Integer, primary_key=True, autoincrement=True)
    strategy_name = Column(String(100), nullable=False, index=True)
    version = Column(Integer, nullable=False)
    is_active = Column(Boolean, default=False, index=True)
    description = Column(String(500), nullable=True)
    definition = Column(JSON, nullable=False)
    created_at = Column(DateTime, default=lambda: datetime.now(timezone.utc), index=True)

    def __repr__(self) -> str:
        return f"<StrategyDefinition(name={self.strategy_name}, v={self.version}, active={self.is_active})>"


# ── IPO Analysis Module ────────────────────────────────────────────────────────
# Independent of the trading/strategy/backtest tables above — the IPO module
# reads and writes only these tables, never the trading ones.

class IPOIssueModel(Base):
    """
    One row per IPO. `raw_data` keeps the full source payload (from NSE)
    verbatim, so newly-noticed fields don't require a migration — every
    named column below is just a convenience extraction of what's already
    in raw_data, never a value invented independently of it.
    """
    __tablename__ = "ipo_issues"

    id = Column(Integer, primary_key=True, autoincrement=True)
    symbol = Column(String(50), nullable=False, unique=True, index=True)
    company_name = Column(String(300), nullable=False)
    status = Column(String(20), nullable=False, index=True)  # UPCOMING, OPEN, CLOSED, LISTED
    security_type = Column(String(20), nullable=True)  # EQ, SME
    price_band_low = Column(Float, nullable=True)
    price_band_high = Column(Float, nullable=True)
    lot_size = Column(Integer, nullable=True)
    issue_size = Column(Float, nullable=True)  # number of shares offered
    issue_start_date = Column(DateTime, nullable=True)
    issue_end_date = Column(DateTime, nullable=True)
    listing_date = Column(DateTime, nullable=True)
    listing_price = Column(Float, nullable=True)
    source = Column(String(50), default="NSE")
    raw_data = Column(JSON, nullable=True)
    created_at = Column(DateTime, default=lambda: datetime.now(timezone.utc))
    updated_at = Column(DateTime, default=lambda: datetime.now(timezone.utc), onupdate=lambda: datetime.now(timezone.utc))

    def __repr__(self) -> str:
        return f"<IPOIssue(symbol={self.symbol}, status={self.status})>"


class IPOSubscriptionSnapshotModel(Base):
    """
    Time-series subscription data — how many times a category was
    subscribed, at the moment it was collected. An IPO's subscription
    changes throughout its open window, so this is append-only, not a
    single current value on IPOIssueModel.
    """
    __tablename__ = "ipo_subscription_snapshots"

    id = Column(Integer, primary_key=True, autoincrement=True)
    ipo_symbol = Column(String(50), nullable=False, index=True)
    category = Column(String(50), nullable=False)  # Total, QIB, NII, Retail, etc. (as NSE reports them)
    shares_offered = Column(Float, nullable=True)
    shares_bid = Column(Float, nullable=True)
    subscription_times = Column(Float, nullable=True)  # noOfTime from NSE — the actual subscription multiple
    snapshot_at = Column(DateTime, default=lambda: datetime.now(timezone.utc), index=True)

    def __repr__(self) -> str:
        return f"<IPOSubscription(symbol={self.ipo_symbol}, category={self.category}, x={self.subscription_times})>"


class IPOAnalystReportModel(Base):
    """One employee's analysis of one IPO. Score/confidence must be derived
    from real stored data (IPOIssueModel / IPOSubscriptionSnapshotModel) —
    an analyst with no real data for its specialty does not produce a row
    here rather than inventing a number."""
    __tablename__ = "ipo_analyst_reports"

    id = Column(Integer, primary_key=True, autoincrement=True)
    ipo_symbol = Column(String(50), nullable=False, index=True)
    analyst_name = Column(String(100), nullable=False, index=True)
    score = Column(Float, nullable=False)  # 0-100
    confidence = Column(Float, nullable=False)  # 0-100
    reason = Column(String(1000), nullable=False)
    advantages = Column(JSON, nullable=True)  # list[str]
    risks = Column(JSON, nullable=True)  # list[str]
    created_at = Column(DateTime, default=lambda: datetime.now(timezone.utc), index=True)

    def __repr__(self) -> str:
        return f"<IPOAnalystReport(symbol={self.ipo_symbol}, analyst={self.analyst_name}, score={self.score})>"


class IPORecommendationModel(Base):
    """The IPO CEO's final recommendation, aggregating whichever analyst
    reports actually exist for this IPO at the time it was generated."""
    __tablename__ = "ipo_recommendations"

    id = Column(Integer, primary_key=True, autoincrement=True)
    ipo_symbol = Column(String(50), nullable=False, index=True)
    recommendation = Column(String(30), nullable=False)  # APPLY, AVOID, LISTING_GAIN_ONLY, LONG_TERM_INVESTMENT, WAIT
    confidence = Column(Float, nullable=False)
    reasoning = Column(String(2000), nullable=False)
    analysts_used = Column(JSON, nullable=True)  # list[str] of analyst_name that contributed
    data_completeness_pct = Column(Float, default=0.0)  # analysts_used / total analysts in the registry
    created_at = Column(DateTime, default=lambda: datetime.now(timezone.utc), index=True)

    def __repr__(self) -> str:
        return f"<IPORecommendation(symbol={self.ipo_symbol}, rec={self.recommendation})>"


class IPOPerformanceModel(Base):
    """Post-listing comparison of what the CEO predicted vs what actually
    happened — the feedback loop for future trust-scoring of analysts."""
    __tablename__ = "ipo_performance"

    id = Column(Integer, primary_key=True, autoincrement=True)
    ipo_symbol = Column(String(50), nullable=False, unique=True, index=True)
    predicted_recommendation = Column(String(30), nullable=False)
    predicted_confidence = Column(Float, nullable=False)
    issue_price_high = Column(Float, nullable=True)
    listing_price = Column(Float, nullable=True)
    listing_gain_pct = Column(Float, nullable=True)
    was_correct = Column(Boolean, nullable=True)  # null until judged
    evaluated_at = Column(DateTime, default=lambda: datetime.now(timezone.utc))

    def __repr__(self) -> str:
        return f"<IPOPerformance(symbol={self.ipo_symbol}, gain={self.listing_gain_pct})>"
