from datetime import datetime, timezone
from typing import Any, Dict, Optional
from sqlalchemy import Column, Integer, String, Float, DateTime, JSON, ForeignKey, Boolean
from sqlalchemy.orm import relationship
from database.connection import Base

class ConfigurationModel(Base):
    """Stores system-wide dynamic configuration values."""
    __tablename__ = "configurations"

    key = Column(String(100), primary_key=True)
    value = Column(String(500), nullable=False)
    description = Column(String(250), nullable=True)
    updated_at = Column(DateTime, default=lambda: datetime.now(timezone.utc), onupdate=lambda: datetime.now(timezone.utc))

    def __repr__(self) -> str:
        return f"<Configuration(key={self.key}, value={self.value})>"


class MarketDataModel(Base):
    """Stores historical and real-time market price data (ticks/candles)."""
    __tablename__ = "market_data"

    id = Column(Integer, primary_key=True, autoincrement=True)
    symbol = Column(String(50), nullable=False, index=True)
    timestamp = Column(DateTime, nullable=False, index=True)
    interval = Column(String(10), default="1m", nullable=False, index=True)  # tick, 1m, 5m, 1h, etc.
    open = Column(Float, nullable=False)
    high = Column(Float, nullable=False)
    low = Column(Float, nullable=False)
    close = Column(Float, nullable=False)
    volume = Column(Float, nullable=False)

    def __repr__(self) -> str:
        return f"<MarketData(symbol={self.symbol}, time={self.timestamp}, close={self.close})>"


class IndicatorModel(Base):
    """Stores calculated technical or ML indicators associated with symbols."""
    __tablename__ = "indicators"

    id = Column(Integer, primary_key=True, autoincrement=True)
    symbol = Column(String(50), nullable=False, index=True)
    name = Column(String(100), nullable=False, index=True)  # RSI, MACD, custom-ml-model
    timestamp = Column(DateTime, nullable=False, index=True)
    values = Column(JSON, nullable=False)  # Dictionary of calculated components

    def __repr__(self) -> str:
        return f"<Indicator(name={self.name}, symbol={self.symbol}, time={self.timestamp})>"


class OrderModel(Base):
    """Tracks state and parameters of trading orders."""
    __tablename__ = "orders"

    id = Column(String(100), primary_key=True)  # Client Order ID (uuid / custom prefix)
    broker_order_id = Column(String(100), nullable=True, index=True)
    symbol = Column(String(50), nullable=False, index=True)
    side = Column(String(10), nullable=False)  # BUY, SELL
    type = Column(String(20), nullable=False)  # MARKET, LIMIT, STOP_LIMIT
    price = Column(Float, nullable=True)
    quantity = Column(Float, nullable=False)
    status = Column(String(30), nullable=False, index=True)  # PENDING, SUBMITTED, FILLED, REJECTED, CANCELLED
    broker = Column(String(50), nullable=False)  # paper, kotak, etc.
    created_at = Column(DateTime, default=lambda: datetime.now(timezone.utc))
    updated_at = Column(DateTime, default=lambda: datetime.now(timezone.utc), onupdate=lambda: datetime.now(timezone.utc))

    # Relationship to trades
    trades = relationship("TradeModel", back_populates="order", cascade="all, delete-orphan")

    def __repr__(self) -> str:
        return f"<Order(id={self.id}, symbol={self.symbol}, side={self.side}, status={self.status})>"


class TradeModel(Base):
    """Tracks actual executions (fills) of orders."""
    __tablename__ = "trades"

    id = Column(String(100), primary_key=True)  # Trade execution ID from broker or system
    order_id = Column(String(100), ForeignKey("orders.id"), nullable=False, index=True)
    symbol = Column(String(50), nullable=False, index=True)
    side = Column(String(10), nullable=False)  # BUY, SELL
    price = Column(Float, nullable=False)
    quantity = Column(Float, nullable=False)
    commission = Column(Float, default=0.0)
    executed_at = Column(DateTime, default=lambda: datetime.now(timezone.utc), index=True)
    broker = Column(String(50), nullable=False)

    order = relationship("OrderModel", back_populates="trades")

    def __repr__(self) -> str:
        return f"<Trade(id={self.id}, order_id={self.order_id}, price={self.price}, quantity={self.quantity})>"


class AgentReportModel(Base):
    """Stores analytical outputs, heartbeats, or audits generated by agents."""
    __tablename__ = "agent_reports"

    id = Column(Integer, primary_key=True, autoincrement=True)
    agent_name = Column(String(100), nullable=False, index=True)
    report_type = Column(String(50), nullable=False, index=True)  # performance, risk_analysis, health
    data = Column(JSON, nullable=False)  # Arbitrary payload
    created_at = Column(DateTime, default=lambda: datetime.now(timezone.utc), index=True)

    def __repr__(self) -> str:
        return f"<AgentReport(agent={self.agent_name}, type={self.report_type})>"


class JournalModel(Base):
    """Stores logs, decisions, or text diaries (trading journal)."""
    __tablename__ = "journal"

    id = Column(Integer, primary_key=True, autoincrement=True)
    entry_type = Column(String(50), default="system", index=True)  # system, manual, risk_decision, strategy_note
    text = Column(String(2000), nullable=False)
    tags = Column(JSON, nullable=True)  # List of string tags ["BTC", "risk_limit", "cooldown"]
    created_at = Column(DateTime, default=lambda: datetime.now(timezone.utc), index=True)

    def __repr__(self) -> str:
        return f"<Journal(type={self.entry_type}, time={self.created_at})>"


class PerformanceModel(Base):
    """Stores periodic snapshots of portfolio health metrics."""
    __tablename__ = "performance"

    id = Column(Integer, primary_key=True, autoincrement=True)
    equity = Column(Float, nullable=False)
    pnl = Column(Float, nullable=False)
    drawdown_percent = Column(Float, nullable=False)
    sharpe_ratio = Column(Float, default=0.0)
    metrics = Column(JSON, nullable=True)  # Dictionary containing win_rate, total_trades, profit_factor etc.
    timestamp = Column(DateTime, default=lambda: datetime.now(timezone.utc), index=True)

    def __repr__(self) -> str:
        return f"<Performance(equity={self.equity}, pnl={self.pnl}, time={self.timestamp})>"


class StrategyDefinitionModel(Base):
    """
    Standardized, engine-agnostic strategy definition produced by the
    Strategy Studio. `definition` is a JSON blob matching the
    strategies.models.Strategy pydantic schema (rules, exit_rules, actions)
    — the same schema strategies/engine.py already evaluates, and the same
    one YAML-file strategies use, so any consumer (live decision pipeline,
    backtest replay, future modules) reads strategies the same way
    regardless of where they were authored.

    Versioned: every save is a new immutable row. Exactly one version per
    strategy_name may have is_active=True at a time — that's the version
    StrategyEngine loads and evaluates.
    """
    __tablename__ = "strategy_definitions"

    id = Column(Integer, primary_key=True, autoincrement=True)
    strategy_name = Column(String(100), nullable=False, index=True)
    version = Column(Integer, nullable=False)
    is_active = Column(Boolean, default=False, index=True)
    description = Column(String(500), nullable=True)
    definition = Column(JSON, nullable=False)
    created_at = Column(DateTime, default=lambda: datetime.now(timezone.utc), index=True)

    def __repr__(self) -> str:
        return f"<StrategyDefinition(name={self.strategy_name}, v={self.version}, active={self.is_active})>"
